/**
 * Universal player for audio sprites generated by the 'audiosprite' tool.
 * Requires an AudioContext and fetch to be injected.
 * Uses AudioBufferQueueSourceNode and buffer splitting for mobile stability.
 */

/**
 * Defines the available audio routing channels.
 * - 'sfx': Short sound effects (coins, jumps, UI). High priority, usually usually non-looping.
 * - 'music': Background tracks. Lower priority, usually looping, separate volume control.
 */
export type AudioChannel = 'sfx' | 'music';

/**
 * Configuration options for playing a specific sound sprite.
 */
export interface PlayOptions {
  /**
   * Specifies which mixer channel to route the audio through.
   * Use 'music' for BGM to ensure it responds to music volume settings.
   * @default 'sfx'
   */
  channel?: AudioChannel;

  /**
   * Force the sound to loop (or not), overriding the setting
   * defined in the original audiosprite JSON manifest.
   */
  loop?: boolean;

  /**
   * Playback speed/pitch multiplier.
   * 1.0 is normal speed. Values > 1.0 are faster/higher pitch; values < 1.0 are slower/lower pitch.
   * @default 1.0
   */
  pitch?: number;

  /**
   * Stereo panning value between -1.0 (full left) and 1.0 (full right).
   * @default 0.0 (center)
   */
  pan?: number;

  /**
   * Cooldown duration in milliseconds to prevent the sound from triggering too fast.
   */
  throttleMs?: number;
}

export interface AudioSpritePlayerConfig {
  audioContext: any | null;
  fetch: any;
  platform: string;
  debug?: boolean;
}

export class AudioSpritePlayer {
  audioContext: any | null;
  fetch: any | null;
  audioBuffer: any | null; // The full audio buffer
  manifest: any | null;
  platform: string;
  private debug: boolean;
  // Cache for the small, pre-split AudioBuffers used by mobile's QueueSourceNode
  private spriteBufferCache: Record<string, any> = {};
  private loopingSource: any | null = null;
  private sourcePool: any[] = []; // NEW: Pool for non-looping sources
  private maxPoolSize: number = 5; // Adjust this based on testing (5 is a good start)
  private lastPlayedTimestamps: Record<string, number> = {};

  // NEW: The Mixer
  public masterGain: any;
  public sfxGain: any;
  public musicGain: any;

  constructor({
    audioContext,
    fetch,
    platform,
    debug = false,
  }: AudioSpritePlayerConfig) {
    this.debug = debug;
    if (!audioContext) {
      if (platform === 'web') {
        // Web doesnt need to provide AudioContext
        // @ts-ignore
        this.audioContext = new AudioContext();
      } else {
        throw new Error(
          'An AudioContext instance must be provided from react-native-audio-api.'
        );
      }
    }
    if (!fetch) {
      throw new Error('A fetch implementation must be provided.');
    }
    this.audioContext = audioContext;
    this.fetch = fetch;
    this.audioBuffer = null;
    this.manifest = null;
    this.platform = platform; // 'web', 'ios', 'android', etc.
    if (
      this.audioContext?.createBufferSource?.constructor?.name ===
      'AsyncFunction'
    ) {
      this.log(
        'createBufferSource is async! going with web default AudioContext'
      );
      // Can be removed after this PR gets merged
      //https://github.com/software-mansion/react-native-audio-api/issues/574
      // @ts-ignore
      this.audioContext = new AudioContext();
    }

    // 1. Create Master Output
    this.masterGain = this.audioContext.createGain();
    this.masterGain.gain.value = 1.0;
    this.masterGain.connect(this.audioContext.destination);

    // 2. Create Channels
    this.sfxGain = this.audioContext.createGain();
    this.sfxGain.gain.value = 1.0;
    this.sfxGain.connect(this.masterGain); // Connect to Master

    this.musicGain = this.audioContext.createGain();
    this.musicGain.gain.value = 1.0;
    this.musicGain.connect(this.masterGain); // Connect to Master
  }

  private log(message: string, ...optionalParams: any[]) {
    if (this.debug) {
      console.log(message, ...optionalParams);
    }
  }

  /**
   * Caches pre-split AudioBuffers for each sprite, which is necessary
   * for stable playback on mobile using the BufferQueueSourceNode.
   *
   * This method iterates through the audio sprite manifest and creates a separate
   * AudioBuffer for each sound sprite. These smaller buffers are then stored
   * in `this.spriteBufferCache` for efficient playback on mobile platforms,
   * especially when using `AudioBufferQueueSourceNode`.
   *
   * The `audiosprite` manifest is expected to have the following structure for each sprite:
   * `[start_time_ms, duration_ms, loop_boolean (optional)]`
   *
   * @example
   * // Example audiosprite manifest structure:
   * {
   *   "urls": ["audio.mp3", "audio.ogg"],
   *   "sprite": {
   *     "sound1": [0, 1000, false],       // start at 0ms, duration 1000ms, no loop
   *     "sound2": [1500, 500, true],      // start at 1500ms, duration 500ms, loop
   *     "background": [2000, 30000, true] // start at 2000ms, duration 30000ms, loop
   *   }
   * }
   */
  private _cacheSpriteBuffers() {
    if (!this.audioBuffer || !this.manifest) {
      return;
    }

    const sampleRate = this.audioBuffer.sampleRate;
    const numChannels = this.audioBuffer.numberOfChannels;
    this.spriteBufferCache = {};

    for (const soundName in this.manifest.sprite) {
      const sound = this.manifest.sprite[soundName];

      // Calculate frame indices based on audiosprite format: [start, duration, loop]
      const startFrame = Math.floor((sound[0] * sampleRate) / 1000); // Convert ms to frames
      const endFrame = Math.ceil(((sound[0] + sound[1]) * sampleRate) / 1000); // Convert ms to frames
      const durationFrames = endFrame - startFrame;

      if (durationFrames <= 0) {
        console.warn(
          `Sprite "${soundName}" has zero or negative duration. Skipping.`
        );
        continue;
      }

      // 1. Create a new empty buffer for the sprite
      const spriteBuffer = this.audioContext.createBuffer(
        numChannels,
        durationFrames,
        sampleRate
      );

      // 2. Copy data from the full buffer to the new sprite buffer
      for (let i = 0; i < numChannels; i++) {
        const sourceData = this.audioBuffer.getChannelData(i);
        const destinationData = spriteBuffer.getChannelData(i);

        // Extract the segment data (efficient array copy)
        const segment = sourceData.subarray(startFrame, endFrame);
        destinationData.set(segment);
      }

      this.spriteBufferCache[soundName] = spriteBuffer;
      this.log(
        `RNAS: Cached sprite buffer for ${soundName}, frames: ${durationFrames}`
      );
      const ch0 = spriteBuffer.getChannelData(0);
      let maxVal = 0;
      for (let i = 0; i < Math.min(ch0.length, 1000); i++) {
        const v = Math.abs(ch0[i]);
        if (v > maxVal) maxVal = v;
      }
      this.log(
        `RNAS: Sprite ${soundName} max amplitude (first 1000): ${maxVal}`
      );
    }
  }

  /**
   * Retrieves a source node from the pool or creates a new one if the pool is under capacity.
   */
  private _getOrCreateSourceNode(): any {
    if (this.platform === 'web') {
      // Web logic remains simple: always create a standard AudioBufferSourceNode
      const source = this.audioContext.createBufferSource();
      // source.connect(this.audioContext.destination);
      return source;
    }

    // Mobile/QueueSourceNode logic
    let source;
    if (this.sourcePool.length > 0) {
      source = this.sourcePool.pop(); // Reuse an available source
      // Disconnect the previous onEnded/onBufferEnded handler if it had one
      if (this.platform !== 'web') {
        source.onBufferEnded = null;
      } else {
        source.onEnded = null;
      }
      // console.log('Reusing source from pool. Pool size:', this.sourcePool.length);
    } else if (this.sourcePool.length < this.maxPoolSize) {
      // Create a new source if pool is not full
      if (!this.audioContext.createBufferQueueSource) {
        console.error(
          'RNAS Error: createBufferQueueSource is not available. Cannot create pool.'
        );
        return null;
      }
      source = this.audioContext.createBufferQueueSource();
      this.log('RNAS: Created new BufferQueueSource.');
      // source.connect(this.audioContext.destination);
      // console.log('Created new source. Pool size:', this.sourcePool.length);
    } else {
      // If pool is full, we might have to block or fail.
      // For simplicity, we'll return null and warn, but a robust system
      // might implement a "wait-and-retry" mechanism.
      console.warn(
        'RNAS Warning: Source pool is full. Dropping non-looping sound.'
      );
      return null;
    }

    // Define the cleanup/recycling function
    const cleanupAndRecycle = () => {
      // Only recycle if we are under maxPoolSize and it's not the looping source
      if (this.sourcePool.length < this.maxPoolSize) {
        this.sourcePool.push(source);
        // console.log('Recycled source. Pool size:', this.sourcePool.length);
      } else {
        // Explicitly clear callbacks to release JSI values on the JS thread before GC
        if (this.platform !== 'web') {
          source.onBufferEnded = null;
        } else {
          source.onEnded = null;
        }
        // If pool is full, let it be garbage collected
        source.disconnect();
        // console.log('Source disconnected (GC candidate).');
      }
    };

    // Assign the cleanup function to run when the sound finishes playing
    if (this.platform !== 'web') {
      source.onBufferEnded = cleanupAndRecycle;
    } else {
      source.onEnded = cleanupAndRecycle;
    }

    return source;
  }

  async load(json: any, audio?: any) {
    try {
      let decodedBuffer: any;

      // --- Fetching and Decoding Logic (Uses existing logic) ---
      if (typeof json === 'string') {
        const response = await this.fetch(json);
        if (!response.ok) {
          throw new Error(`Failed to fetch manifest: ${response.statusText}`);
        }
        this.manifest = await response.json();

        if (!this.manifest.urls || !this.manifest.sprite) {
          throw new Error(
            'Invalid audiosprite manifest format. Missing "urls" or "sprite".'
          );
        }

        const audioFileName = this.manifest.urls[0];
        const audioUrl = new URL(audioFileName, response.url).href;

        if (this.platform === 'web') {
          const audioResponse = await this.fetch(audioUrl);
          if (!audioResponse.ok) {
            throw new Error(
              `Failed to fetch audio file: ${audioResponse.statusText}`
            );
          }
          const arrayBuffer = await audioResponse.arrayBuffer();
          decodedBuffer = await this.audioContext.decodeAudioData(arrayBuffer);
        } else {
          // Native platforms support decoding strings directly (fetches natively/decodes from file path)
          decodedBuffer = await this.audioContext.decodeAudioData(audioUrl);
        }
      } else {
        this.manifest = json;
        if (!this.manifest.urls || !this.manifest.sprite) {
          throw new Error(
            'Invalid audiosprite manifest format. Missing "urls" or "sprite".'
          );
        }

        if (typeof audio === 'string') {
          if (this.platform === 'web') {
            const audioResponse = await this.fetch(audio);
            if (!audioResponse.ok) {
              throw new Error(
                `Failed to fetch audio file: ${audioResponse.statusText}`
              );
            }
            const arrayBuffer = await audioResponse.arrayBuffer();
            decodedBuffer =
              await this.audioContext.decodeAudioData(arrayBuffer);
          } else {
            // Native platforms support decoding strings directly (fetches natively/decodes from file path)
            decodedBuffer = await this.audioContext.decodeAudioData(audio);
          }
        } else {
          // 🔑 CRITICAL FIX: Create a typed array view before decoding
          // This ensures the data is treated as a true ArrayBuffer in the audio context.
          const typedArrayView = new Uint8Array(audio);
          decodedBuffer = await this.audioContext.decodeAudioData(
            typedArrayView.buffer
          );
        }
      }
      // --- End Fetching and Decoding Logic ---

      this.audioBuffer = decodedBuffer;

      // 🚨 CRITICAL: Split and cache buffers for mobile stability/correctness
      this._cacheSpriteBuffers();

      this.log('RNAS: Audio sprite loaded successfully.');
    } catch (error) {
      console.error('Failed to load audio sprite:', error);
      throw error; // Re-throw for user to catch
    }
  }

  async play(soundName: string, options?: PlayOptions) {
    this.log(
      `RNAS play(): ${soundName} on ${this.platform}, contextState=${this.audioContext?.state}`
    );
    if (!this.audioBuffer || !this.manifest) {
      console.warn('Audio sprite not loaded. Call load() first.');
      return;
    }

    // Throttle support
    if (options?.throttleMs !== undefined) {
      const now = Date.now();
      const lastPlayed = this.lastPlayedTimestamps[soundName] || 0;
      if (now - lastPlayed < options.throttleMs) {
        return;
      }
      this.lastPlayedTimestamps[soundName] = now;
    }

    // Resume context if it was suspended
    if (this.audioContext.state === 'suspended') {
      await this.audioContext.resume();
      this.log('RNAS: After resume, contextState=', this.audioContext.state);
    }

    const sound = this.manifest.sprite[soundName];
    if (!sound) {
      console.warn(`Sound "${soundName}" not found in spritemap.`);
      return;
    }

    const duration = sound[1];
    if (duration <= 0) {
      console.warn(`Sound "${soundName}" has invalid duration.`);
      return;
    }

    // 1. Determine Channel (Default to 'sfx')
    const channel = options?.channel || 'sfx';
    const targetNode = channel === 'music' ? this.musicGain : this.sfxGain;

    // 2. Determine Loop (Options override Manifest)
    // defined in your existing code as: const sound = this.manifest.sprite[soundName];
    // const manifestLoop = sound[2];
    const loop = options?.loop !== undefined ? options.loop : sound[2];

    let source: any;
    const spriteBuffer = this.spriteBufferCache[soundName];

    // 🚨 MOBILE LOGIC: Use AudioBufferQueueSourceNode with cached split buffer
    if (this.platform !== 'web') {
      if (!spriteBuffer) {
        console.error(
          `RNAS Error: Split buffer for "${soundName}" not found in cache.`
        );
        return;
      }

      if (!this.audioContext.createBufferQueueSource) {
        console.error(
          'RNAS Error: createBufferQueueSource is not available on this native platform.'
        );
        return;
      }

      if (loop) {
        // Always use AudioBufferQueueSourceNode
        source = this.audioContext.createBufferQueueSource();
        this.log('RNAS: Created looping BufferQueueSource');

        // Apply pitch/playbackRate if requested
        if (options?.pitch !== undefined && source.playbackRate) {
          source.playbackRate.value = options.pitch;
        }

        // Apply pan if requested and supported
        let outputNode = targetNode;
        if (
          options?.pan !== undefined &&
          this.audioContext.createStereoPanner
        ) {
          try {
            const panner = this.audioContext.createStereoPanner();
            panner.pan.value = options.pan;
            panner.connect(targetNode);
            outputNode = panner;
          } catch (err) {
            console.warn('Failed to create StereoPannerNode:', err);
          }
        }

        source.enqueueBuffer(spriteBuffer);
        this.log('RNAS: Enqueued buffer for looping source');
        source.connect(outputNode);
        this.log('RNAS: Connected looping source to output');

        // Manual looping using onEnded/onBufferEnded
        const loopHandler = () => {
          // Only re-enqueue if this is still the active looping source
          if (this.loopingSource === source) {
            source.enqueueBuffer(spriteBuffer);
            // Restart the source immediately after re-enqueueing
            source.start(0, 0);
          }
        };
        if (this.platform !== 'web') {
          source.onBufferEnded = loopHandler;
        } else {
          source.onEnded = loopHandler;
        }

        // Stop any currently playing looping source before starting a new one
        if (this.loopingSource) {
          this.loopingSource.stop();
        }
        source.start(0, 0); // Start immediately
        this.log('RNAS: Started looping source');
        this.loopingSource = source; // Store reference to looping source
      } else {
        // **NEW: USE POOL FOR NON-LOOPING MOBILE SOUNDS**
        source = this._getOrCreateSourceNode();
        if (!source) return; // Dropped sound because pool was full

        // Reconnect to the correct channel (since pooled nodes might have been connected elsewhere)
        source.disconnect();

        // Apply pitch/playbackRate if requested (or reset it to 1.0)
        if (source.playbackRate) {
          source.playbackRate.value =
            options?.pitch !== undefined ? options.pitch : 1.0;
        }

        // Apply pan if requested and supported
        let outputNode = targetNode;
        if (
          options?.pan !== undefined &&
          this.audioContext.createStereoPanner
        ) {
          try {
            const panner = this.audioContext.createStereoPanner();
            panner.pan.value = options.pan;
            panner.connect(targetNode);
            outputNode = panner;
          } catch (err) {
            console.warn('Failed to create StereoPannerNode:', err);
          }
        }
        source.connect(outputNode);
        this.log('RNAS: Connected pooled source to output');

        // Must re-enqueue the buffer since the source was reused
        source.enqueueBuffer(spriteBuffer);
        this.log('RNAS: Enqueued buffer for pooled source');

        // Start immediately (start time 0 for BufferQueueSourceNode means "as soon as possible")
        source.start(0, 0);
        this.log('RNAS: Started pooled source');
      }
    } else {
      // 🌐 WEB LOGIC (Standard Web Audio API)
      source = this.audioContext.createBufferSource();

      if (!source || typeof source.connect !== 'function') {
        console.error(
          'RNAS Error: createBufferSource() returned an invalid object on web. Aborting playback.'
        );
        return;
      }

      source.buffer = spriteBuffer;

      // Apply pitch/playbackRate if requested
      if (options?.pitch !== undefined && source.playbackRate) {
        source.playbackRate.value = options.pitch;
      }

      // Apply pan if requested and supported
      let outputNode = targetNode;
      if (options?.pan !== undefined && this.audioContext.createStereoPanner) {
        try {
          const panner = this.audioContext.createStereoPanner();
          panner.pan.value = options.pan;
          panner.connect(targetNode);
          outputNode = panner;
        } catch (err) {
          console.warn('Failed to create StereoPannerNode:', err);
        }
      }
      source.connect(outputNode);

      // const loop = sound[2]; // audiosprite stores loop as the third element in the array
      if (loop) {
        source.loop = true;
        source.loopStart = 0; // Relative to the spriteBuffer
        source.loopEnd = sound[1] / 1000; // Duration of the spriteBuffer

        // Stop any currently playing looping source before starting a new one
        if (this.loopingSource) {
          this.loopingSource.stop();
        }
        source.start(0); // Start immediately, no offset for the individual spriteBuffer
        this.loopingSource = source; // Store reference to looping source
      } else {
        // Use the 'audiosprite' format: start(when, offset, duration)
        source.start(
          0, // Start playing now
          0, // The offset in seconds (relative to the spriteBuffer)
          sound[1] / 1000 // The calculated duration in seconds
        );
      }
    }

    this.log(`RNAS: played ${soundName} on ${this.platform}`);
  }

  getManifest() {
    return this.manifest;
  }

  getAudioBuffer() {
    return this.audioBuffer;
  }

  /**
   * Smoothly fades in a background music track over the specified duration.
   */
  fadeInMusic(soundName: string, durationMs: number, options?: PlayOptions) {
    if (!this.musicGain) return;

    // Stop any existing loop first
    this.stop();

    // Start with volume 0
    this.musicGain.gain.setValueAtTime(0, this.audioContext.currentTime);

    // Play the music
    this.play(soundName, {
      ...options,
      channel: 'music',
      loop: true,
    });

    // Fade to target volume (default to 1.0)
    const targetVolume =
      this.musicGain.gain.value > 0 ? this.musicGain.gain.value : 1.0;
    this.musicGain.gain.linearRampToValueAtTime(
      targetVolume,
      this.audioContext.currentTime + durationMs / 1000
    );
  }

  /**
   * Smoothly fades out the background music over the specified duration.
   */
  fadeOutMusic(durationMs: number) {
    if (!this.musicGain || !this.loopingSource) return;

    const sourceToStop = this.loopingSource;
    const initialVolume = this.musicGain.gain.value;

    this.musicGain.gain.setValueAtTime(
      initialVolume,
      this.audioContext.currentTime
    );
    this.musicGain.gain.linearRampToValueAtTime(
      0,
      this.audioContext.currentTime + durationMs / 1000
    );

    // Stop the actual source once the fade completes, and restore gain
    setTimeout(() => {
      if (this.loopingSource === sourceToStop) {
        this.stop();
        // Restore music gain volume for future plays
        this.musicGain.gain.setValueAtTime(
          initialVolume,
          this.audioContext.currentTime
        );
      }
    }, durationMs);
  }

  /**
   * Stops the currently looping audio sprite.
   * If a looping sound is playing, it will be stopped immediately.
   */
  stop() {
    if (this.loopingSource) {
      if (this.platform !== 'web') {
        this.loopingSource.onBufferEnded = null;
      } else {
        this.loopingSource.onEnded = null;
      }
      this.loopingSource.stop();
      this.loopingSource = null;
      this.log('RNAS: Looping audio stopped.');
    } else {
      this.log('RNAS: No looping audio to stop.');
    }
  }

  /**
   * Sets the volume for background music only.
   * @param value 0.0 to 1.0
   */
  setMusicVolume(value: number) {
    if (this.musicGain) {
      // secure against uninitialized context
      this.musicGain.gain.setTargetAtTime(
        value,
        this.audioContext.currentTime,
        0.02
      );
    }
  }

  /**
   * Sets the volume for sound effects only.
   * @param value 0.0 to 1.0
   */
  setSFXVolume(value: number) {
    if (this.sfxGain) {
      this.sfxGain.gain.setTargetAtTime(
        value,
        this.audioContext.currentTime,
        0.02
      );
    }
  }

  /**
   * Sets the Global Master Volume (affects both Music and SFX).
   * @param value 0.0 to 1.0
   */
  set volume(value: number) {
    if (this.masterGain) {
      this.masterGain.gain.setTargetAtTime(
        value,
        this.audioContext.currentTime,
        0.02
      );
    }
  }

  // Master Volume getter
  get volume(): number {
    return this.masterGain?.gain?.value ?? 1.0;
  }
}
